feat: Mega Man channel
GamesDoneQuick/gdq-break-channels pull request #7
Opened 2023-05-30 19:59 UTC by Suyooo

### Description
This is a channel based off of Mega Man. Mega Man powerwalks through MM2 Wily 1, shooting at enemies spawned by donations. They'll drop pickups, with the larger versions dropping for big donations or donation trains.

![Peek 2023-05-30 21-27](https://github.com/GamesDoneQuick/gdq-break-channels/assets/5811591/4a5a45fc-7bb0-489e-adf9-a19b54cbebd1)

One major aspect is that the donation total is not fully live: when a donation comes in, the donation total stays the same until the pickup is collected. At this point, all animations stop, and the donation total counts up to the new value - to recreate the game freezing and the energy bars getting filled, like in the original.  
I'm not 100% sure whether that is okay - I limited the maximum queue length to make sure it doesn't diverge too much - but if you think that's no good, it should be an easy change.

I also took a few liberties with parallax scrolling and positioning, to make it a little more visually interesting :) I'm not much of a React user, so if there's any best practices I've missed and I could implement, please let me know.

### Checklist:
- [x] I have read and followed the requirements in the [**Contributing** document](https://github.com/GamesDoneQuick/gdq-break-channels/blob/main/CONTRIBUTING.md).
- [x] My code has been tested.
- [x] My commit title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) formatting.
- [x] All the code is my own, or is code I have the rights to, and is being made available under the [Apache License Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).
- [x] My channel contains no first-party Nintendo assets.
- [x] I understand that GamesDoneQuick may reject, make changes to, or choose not to show this channel on broadcast, and that discussion or merging does not guarantee the work will be used.

2023-05-30 22:34 UTC, VodBox requested changes
I love this, but I have concerns around the queuing behavior and speed of it. Especially if a bunch of donations come in at once, it can take a long while for the donation total to be brought back up to its realtime value. It may also be correct to the original games, but the enemies scrolling in is awfully slow.

Would it be at all possible to A: speed this up slightly, and B: have donations send out enemies in a row, have Mega Man shoot then all, rather than one at a time, and have Mega Man get the pick ups in succession?

If addressed, should be good to merge.

2023-05-30 23:38 UTC, Suyooo commented
Multiple enemies can now appear at the same time, with a cooldown of slightly less than a second (any shorter, and Mega Man would start jumping over pickups...). This also means the queue can be pretty much removed - since the interval between spawns is now one instead of four seconds, that should still allow most donations to get their own enemy even without the queue.

I kept the code for it in just in case, since I don't think it's significant overhead, I just set the maximum length to one. That way, donations can be merged right away to allow the displayed total to be fairly close to the real one, even during extreme donation trains. Let me know whether it's good now or I should speed it up even more! (It would be possible to merge incoming donations into enemies already on the way, maybe?)

2023-06-01 16:15 UTC, chrishanel approved these changes
From a design standpoint, this has reached a point where I'm good with approving. However, I would love to see more done with the background environment and the variety of enemies if you or someone else has the appetite for it.

2023-06-02 02:24 UTC, VodBox approved these changes

2023-06-02 02:46 UTC, merged

2023-06-02 10:03 UTC, Suyooo commented
> I would love to see more done with the background environment and the variety of enemies if you or someone else has the appetite for it.

I can do that - adding some enemies from all the classic MM games together should pretty much just require adding the sprites for them (maybe give them some new behaviours like bouncing or flying in a wave pattern). And stages from the other games could be added as additional backgrounds, picking a different one each time the channel is loaded. I think I could adapt the code I already have for the clouds to make it easy to add new layers to the existing background or add new ones...

I'll give it a shot in the coming days :)